task-manager.url=localhost:8090

vk.token=
vk.user-id=1029750780
vk.delta-fetching-time=200
vk.url=vk.com
vk.group-ids=106262643

quarkus.http.port=8090
quarkus.log.category."com.fasterxml.jackson".level=DEBUG
quarkus.jackson.fail-on-empty-beans=true
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password =
quarkus.datasource.jdbc.url =

quarkus.rest-client."org.bubna.taskmanager.TaskManagerClient".url=http://localhost:8080/api